-- ==================================================
-- TABLE 1: staff_staff
-- ==================================================
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (1, 'Abdullahi', 'Adisa', 28, 'Male', 'Teacher', 'Full Time', '08093503056', 'abdullahi.adisa1@gracefieldacademy.edu.ng', 112000, '2017-03-15', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (2, 'Funmilayo', 'Balogun', 60, 'Female', 'Teacher', 'Part Time', '09022423884', 'funmilayo.balogun2@gracefieldacademy.edu.ng', 131000, '2016-11-16', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (3, 'Ruth', 'Aliyu', 47, 'Female', 'Teacher', 'Full Time', '08102269166', 'ruth.aliyu3@gracefieldacademy.edu.ng', 108000, '2025-02-25', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (4, 'Precious', 'Alabi', 59, 'Female', 'Teacher', 'Part Time', '08021462704', 'precious.alabi4@gracefieldacademy.edu.ng', 92000, '2013-11-18', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (5, 'Tobi', 'Obi', 43, 'Male', 'Teacher', 'Part Time', '08098095701', 'tobi.obi5@gracefieldacademy.edu.ng', 157000, '2016-03-12', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (6, 'Patience', 'Fashola', 27, 'Female', 'Teacher', 'Full Time', '08068227824', 'patience.fashola6@gracefieldacademy.edu.ng', 164000, '2012-02-24', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (7, 'Blessing', 'Okoro', 36, 'Female', 'Accountant', 'Full Time', '07033150983', 'blessing.okoro7@gracefieldacademy.edu.ng', 232000, '2021-08-17', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (8, 'Chinedu', 'Chukwu', 27, 'Male', 'Principal', 'Full Time', '09073829973', 'chinedu.chukwu8@gracefieldacademy.edu.ng', 358000, '2020-02-17', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (9, 'Uzoamaka', 'Bello', 30, 'Female', 'Teacher', 'Full Time', '08051065133', 'uzoamaka.bello9@gracefieldacademy.edu.ng', 146000, '2021-07-14', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (10, 'Ikenna', 'Mohammed', 32, 'Male', 'Teacher', 'Full Time', '09028108013', 'ikenna.mohammed10@gracefieldacademy.edu.ng', 127000, '2024-04-28', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (11, 'Daniel', 'Nwankwo', 54, 'Male', 'Teacher', 'Full Time', '08124746872', 'daniel.nwankwo11@gracefieldacademy.edu.ng', 143000, '2011-03-13', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (12, 'Aliyu', 'Balogun', 27, 'Male', 'Secretary', 'Full Time', '09018208121', 'aliyu.balogun12@gracefieldacademy.edu.ng', 88000, '2020-01-02', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (13, 'Ibrahim', 'Aliyu', 31, 'Male', 'Teacher', 'Contract', '08066998543', 'ibrahim.aliyu13@gracefieldacademy.edu.ng', 165000, '2017-10-20', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (14, 'Joy', 'Alabi', 49, 'Female', 'Teacher', 'Full Time', '08060799118', 'joy.alabi14@gracefieldacademy.edu.ng', 175000, '2019-08-11', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (15, 'Tobi', 'Alabi', 32, 'Male', 'Teacher', 'Contract', '09028498084', 'tobi.alabi15@gracefieldacademy.edu.ng', 205000, '2012-04-12', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (16, 'Chukwuemeka', 'Alabi', 31, 'Male', 'Teacher', 'Part Time', '08023487401', 'chukwuemeka.alabi16@gracefieldacademy.edu.ng', 187000, '2014-05-10', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (17, 'Mercy', 'Eze', 24, 'Female', 'Teacher', 'Full Time', '07018011280', 'mercy.eze17@gracefieldacademy.edu.ng', 107000, '2018-03-24', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (18, 'Ruth', 'Ude', 33, 'Female', 'Teacher', 'Full Time', '08055331586', 'ruth.ude18@gracefieldacademy.edu.ng', 95000, '2019-06-26', FALSE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (19, 'Ibrahim', 'Adeyemi', 35, 'Male', 'Bursar', 'Full Time', '07013421607', 'ibrahim.adeyemi19@gracefieldacademy.edu.ng', 183000, '2015-12-11', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (20, 'Gbenga', 'Usman', 46, 'Male', 'Teacher', 'Full Time', '08125414586', 'gbenga.usman20@gracefieldacademy.edu.ng', 194000, '2017-04-01', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (21, 'Chioma', 'Ibe', 40, 'Female', 'Teacher', 'Full Time', '07085698169', 'chioma.ibe21@gracefieldacademy.edu.ng', 216000, '2018-01-04', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (22, 'Suleiman', 'Eze', 51, 'Male', 'Teacher', 'Full Time', '08029514846', 'suleiman.eze22@gracefieldacademy.edu.ng', 211000, '2016-06-14', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (23, 'Ijeoma', 'Adisa', 42, 'Female', 'Teacher', 'Full Time', '08149946804', 'ijeoma.adisa23@gracefieldacademy.edu.ng', 115000, '2023-11-13', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (24, 'Blessing', 'Garba', 44, 'Female', 'Teacher', 'Full Time', '08141489513', 'blessing.garba24@gracefieldacademy.edu.ng', 148000, '2016-09-16', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (25, 'Grace', 'Bello', 33, 'Female', 'Teacher', 'Full Time', '09026936763', 'grace.bello25@gracefieldacademy.edu.ng', 122000, '2025-10-28', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (26, 'Chinedu', 'Owolabi', 30, 'Male', 'Bursar', 'Full Time', '08093172788', 'chinedu.owolabi26@gracefieldacademy.edu.ng', 209000, '2015-12-17', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (27, 'Ebele', 'Nwaogu', 56, 'Female', 'Secretary', 'Full Time', '07063487347', 'ebele.nwaogu27@gracefieldacademy.edu.ng', 138000, '2015-12-28', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (28, 'Aliyu', 'Fashola', 41, 'Male', 'Teacher', 'Full Time', '08133166587', 'aliyu.fashola28@gracefieldacademy.edu.ng', 207000, '2012-03-05', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (29, 'Adaeze', 'Balogun', 50, 'Female', 'Teacher', 'Full Time', '07084668893', 'adaeze.balogun29@gracefieldacademy.edu.ng', 191000, '2010-10-13', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (30, 'Grace', 'Afolabi', 51, 'Female', 'Teacher', 'Full Time', '08147298069', 'grace.afolabi30@gracefieldacademy.edu.ng', 141000, '2020-11-22', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (31, 'Ifeanyi', 'Bakare', 51, 'Male', 'Teacher', 'Full Time', '08167556464', 'ifeanyi.bakare31@gracefieldacademy.edu.ng', 151000, '2015-01-09', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (32, 'Kayode', 'Okonkwo', 58, 'Male', 'Teacher', 'Full Time', '08050330923', 'kayode.okonkwo32@gracefieldacademy.edu.ng', 215000, '2021-04-21', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (33, 'Kayode', 'Salami', 31, 'Male', 'Teacher', 'Full Time', '08149912419', 'kayode.salami33@gracefieldacademy.edu.ng', 119000, '2024-12-09', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (34, 'Nnamdi', 'Umeh', 48, 'Male', 'Teacher', 'Full Time', '07031491905', 'nnamdi.umeh34@gracefieldacademy.edu.ng', 184000, '2016-02-19', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (35, 'Bisi', 'Chukwu', 56, 'Female', 'Teacher', 'Full Time', '07087262849', 'bisi.chukwu35@gracefieldacademy.edu.ng', 92000, '2023-08-04', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (36, 'Nkechi', 'Garba', 41, 'Female', 'Teacher', 'Full Time', '09029965075', 'nkechi.garba36@gracefieldacademy.edu.ng', 122000, '2012-05-15', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (37, 'Wale', 'Balogun', 46, 'Male', 'Teacher', 'Full Time', '08090831367', 'wale.balogun37@gracefieldacademy.edu.ng', 135000, '2018-10-23', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (38, 'Kayode', 'Bakare', 55, 'Male', 'Teacher', 'Full Time', '07034957885', 'kayode.bakare38@gracefieldacademy.edu.ng', 92000, '2012-05-08', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (39, 'Esther', 'Suleiman', 46, 'Female', 'Teacher', 'Full Time', '08165182337', 'esther.suleiman39@gracefieldacademy.edu.ng', 126000, '2019-05-08', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (40, 'Ruth', 'Owolabi', 57, 'Female', 'Vice Principal', 'Full Time', '08100824008', 'ruth.owolabi40@gracefieldacademy.edu.ng', 263000, '2016-05-08', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (41, 'Aisha', 'Adegoke', 55, 'Female', 'Teacher', 'Full Time', '08140471167', 'aisha.adegoke41@gracefieldacademy.edu.ng', 92000, '2019-08-16', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (42, 'Friday', 'Adegoke', 27, 'Male', 'Teacher', 'Full Time', '07019993867', 'friday.adegoke42@gracefieldacademy.edu.ng', 196000, '2019-02-08', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (43, 'Patience', 'Ekwueme', 51, 'Female', 'Teacher', 'Full Time', '08163412328', 'patience.ekwueme43@gracefieldacademy.edu.ng', 171000, '2011-10-24', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (44, 'Femi', 'Okafor', 50, 'Male', 'Teacher', 'Full Time', '08107134936', 'femi.okafor44@gracefieldacademy.edu.ng', 168000, '2025-05-02', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (45, 'Ikenna', 'Ogunleye', 33, 'Male', 'Teacher', 'Part Time', '08109947174', 'ikenna.ogunleye45@gracefieldacademy.edu.ng', 198000, '2014-02-02', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (46, 'Mercy', 'Iheanacho', 58, 'Female', 'Teacher', 'Full Time', '07060139904', 'mercy.iheanacho46@gracefieldacademy.edu.ng', 101000, '2011-07-24', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (47, 'Kunle', 'Nwachukwu', 57, 'Male', 'Teacher', 'Full Time', '09071756551', 'kunle.nwachukwu47@gracefieldacademy.edu.ng', 210000, '2018-03-19', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (48, 'Chidi', 'Sani', 55, 'Male', 'Lab Assistant', 'Full Time', '08021680876', 'chidi.sani48@gracefieldacademy.edu.ng', 122000, '2011-08-03', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (49, 'Gbenga', 'Onyekachi', 47, 'Male', 'Teacher', 'Full Time', '08134771093', 'gbenga.onyekachi49@gracefieldacademy.edu.ng', 155000, '2024-01-07', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (50, 'Nnamdi', 'Ude', 24, 'Male', 'Lab Assistant', 'Full Time', '08137484677', 'nnamdi.ude50@gracefieldacademy.edu.ng', 82000, '2017-02-15', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (51, 'David', 'Ude', 33, 'Male', 'Vice Principal', 'Full Time', '07015840449', 'david.ude51@gracefieldacademy.edu.ng', 329000, '2014-02-09', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (52, 'Fatima', 'Mohammed', 58, 'Female', 'Teacher', 'Full Time', '07039636057', 'fatima.mohammed52@gracefieldacademy.edu.ng', 134000, '2022-08-11', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (53, 'Toyin', 'Salami', 33, 'Female', 'Teacher', 'Full Time', '08107187026', 'toyin.salami53@gracefieldacademy.edu.ng', 95000, '2014-09-19', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (54, 'Segun', 'Nwachukwu', 40, 'Male', 'Teacher', 'Full Time', '08096578091', 'segun.nwachukwu54@gracefieldacademy.edu.ng', 181000, '2022-11-03', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (55, 'Aliyu', 'Ogunleye', 29, 'Male', 'Teacher', 'Full Time', '08030504556', 'aliyu.ogunleye55@gracefieldacademy.edu.ng', 103000, '2013-08-06', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (56, 'Ibrahim', 'Onyekachi', 50, 'Male', 'Teacher', 'Full Time', '08129379237', 'ibrahim.onyekachi56@gracefieldacademy.edu.ng', 194000, '2015-03-06', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (57, 'Nkechi', 'Alabi', 24, 'Female', 'Teacher', 'Part Time', '09025946474', 'nkechi.alabi57@gracefieldacademy.edu.ng', 151000, '2019-11-18', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (58, 'Samuel', 'Nwachukwu', 30, 'Male', 'Accountant', 'Full Time', '08100640909', 'samuel.nwachukwu58@gracefieldacademy.edu.ng', 255000, '2021-10-10', FALSE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (59, 'Comfort', 'Ajayi', 38, 'Female', 'Teacher', 'Full Time', '08131047095', 'comfort.ajayi59@gracefieldacademy.edu.ng', 136000, '2017-11-07', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (60, 'Ifeanyi', 'Ojo', 44, 'Male', 'Teacher', 'Full Time', '07088842474', 'ifeanyi.ojo60@gracefieldacademy.edu.ng', 113000, '2016-03-26', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (61, 'Folake', 'Usman', 28, 'Female', 'Teacher', 'Full Time', '08128516048', 'folake.usman61@gracefieldacademy.edu.ng', 217000, '2017-11-24', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (62, 'David', 'Abdullahi', 40, 'Male', 'Receptionist', 'Full Time', '08039859317', 'david.abdullahi62@gracefieldacademy.edu.ng', 112000, '2021-02-22', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (63, 'Uzoamaka', 'Ibe', 32, 'Female', 'Librarian', 'Full Time', '08092675869', 'uzoamaka.ibe63@gracefieldacademy.edu.ng', 95000, '2019-08-04', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (64, 'Daniel', 'Bakare', 30, 'Male', 'Librarian', 'Full Time', '08167735158', 'daniel.bakare64@gracefieldacademy.edu.ng', 171000, '2023-05-02', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (65, 'Adaeze', 'Aliyu', 41, 'Female', 'Receptionist', 'Full Time', '08180053293', 'adaeze.aliyu65@gracefieldacademy.edu.ng', 78000, '2024-02-22', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (66, 'Godwin', 'Balogun', 37, 'Male', 'Teacher', 'Part Time', '08034228421', 'godwin.balogun66@gracefieldacademy.edu.ng', 121000, '2020-03-26', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (67, 'Chukwuemeka', 'Okafor', 46, 'Male', 'Teacher', 'Full Time', '08136811775', 'chukwuemeka.okafor67@gracefieldacademy.edu.ng', 121000, '2020-01-06', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (68, 'Paul', 'Iheanacho', 38, 'Male', 'Teacher', 'Contract', '08057661771', 'paul.iheanacho68@gracefieldacademy.edu.ng', 96000, '2019-08-21', FALSE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (69, 'Okechukwu', 'Chukwuma', 33, 'Male', 'Teacher', 'Full Time', '09028961183', 'okechukwu.chukwuma69@gracefieldacademy.edu.ng', 126000, '2020-07-20', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (70, 'Ebele', 'Ogunleye', 50, 'Female', 'Teacher', 'Full Time', '07015452711', 'ebele.ogunleye70@gracefieldacademy.edu.ng', 149000, '2022-07-24', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (71, 'Ifeanyi', 'Garba', 30, 'Male', 'Teacher', 'Full Time', '08098516560', 'ifeanyi.garba71@gracefieldacademy.edu.ng', 139000, '2014-09-02', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (72, 'Rebecca', 'Akande', 46, 'Female', 'Teacher', 'Full Time', '08105851493', 'rebecca.akande72@gracefieldacademy.edu.ng', 157000, '2016-03-22', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (73, 'Esther', 'Ajayi', 59, 'Female', 'Teacher', 'Full Time', '08105502296', 'esther.ajayi73@gracefieldacademy.edu.ng', 212000, '2018-01-06', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (74, 'Adewale', 'Adekunle', 25, 'Male', 'Teacher', 'Full Time', '08145459910', 'adewale.adekunle74@gracefieldacademy.edu.ng', 160000, '2016-07-14', TRUE);
INSERT INTO staff_staff (id, first_name, last_name, age, gender, role, employment_type, phone_number, email, salary, date_employed, is_active) VALUES (75, 'Femi', 'Owolabi', 27, 'Male', 'Teacher', 'Full Time', '09026438156', 'femi.owolabi75@gracefieldacademy.edu.ng', 126000, '2024-11-14', TRUE);

-- ==================================================
-- TABLE 2: staff_subject
-- ==================================================
INSERT INTO staff_subject (id, name) VALUES (1, 'English Language');
INSERT INTO staff_subject (id, name) VALUES (2, 'Mathematics');
INSERT INTO staff_subject (id, name) VALUES (3, 'Basic Science');
INSERT INTO staff_subject (id, name) VALUES (4, 'Basic Technology');
INSERT INTO staff_subject (id, name) VALUES (5, 'Social Studies');
INSERT INTO staff_subject (id, name) VALUES (6, 'Civic Education');
INSERT INTO staff_subject (id, name) VALUES (7, 'Agricultural Science');
INSERT INTO staff_subject (id, name) VALUES (8, 'Computer Studies');
INSERT INTO staff_subject (id, name) VALUES (9, 'Physical and Health Education');
INSERT INTO staff_subject (id, name) VALUES (10, 'Business Studies');
INSERT INTO staff_subject (id, name) VALUES (11, 'Home Economics');
INSERT INTO staff_subject (id, name) VALUES (12, 'French');
INSERT INTO staff_subject (id, name) VALUES (13, 'Yoruba');
INSERT INTO staff_subject (id, name) VALUES (14, 'Igbo');
INSERT INTO staff_subject (id, name) VALUES (15, 'Hausa');
INSERT INTO staff_subject (id, name) VALUES (16, 'Physics');
INSERT INTO staff_subject (id, name) VALUES (17, 'Chemistry');
INSERT INTO staff_subject (id, name) VALUES (18, 'Biology');
INSERT INTO staff_subject (id, name) VALUES (19, 'Economics');
INSERT INTO staff_subject (id, name) VALUES (20, 'Government');
INSERT INTO staff_subject (id, name) VALUES (21, 'Literature in English');
INSERT INTO staff_subject (id, name) VALUES (22, 'Further Mathematics');
INSERT INTO staff_subject (id, name) VALUES (23, 'Financial Accounting');
INSERT INTO staff_subject (id, name) VALUES (24, 'Commerce');
INSERT INTO staff_subject (id, name) VALUES (25, 'Christian Religious Studies');
INSERT INTO staff_subject (id, name) VALUES (26, 'Islamic Religious Studies');
INSERT INTO staff_subject (id, name) VALUES (27, 'Geography');
INSERT INTO staff_subject (id, name) VALUES (28, 'History');
INSERT INTO staff_subject (id, name) VALUES (29, 'Visual Arts');
INSERT INTO staff_subject (id, name) VALUES (30, 'Music');

-- ==================================================
-- TABLE 3: staff_teachingassignment
-- ==================================================
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (1, 1, 10, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (2, 1, 10, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (3, 1, 10, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (4, 2, 8, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (5, 2, 8, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (6, 3, 7, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (7, 3, 7, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (8, 4, 10, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (9, 4, 11, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (10, 4, 11, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (11, 5, 13, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (12, 5, 13, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (13, 5, 13, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (14, 6, 26, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (15, 6, 26, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (16, 6, 12, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (17, 6, 3, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (18, 9, 14, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (19, 9, 14, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (20, 9, 14, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (21, 9, 19, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (22, 9, 19, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (23, 9, 13, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (24, 10, 30, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (25, 10, 30, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (26, 10, 12, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (27, 10, 12, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (28, 10, 3, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (29, 10, 3, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (30, 10, 3, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (31, 11, 11, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (32, 11, 8, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (33, 11, 8, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (34, 11, 8, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (35, 11, 25, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (36, 11, 25, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (37, 11, 25, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (38, 13, 27, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (39, 13, 21, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (40, 13, 5, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (41, 14, 5, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (42, 14, 25, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (43, 14, 25, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (44, 14, 25, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (45, 14, 21, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (46, 14, 21, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (47, 14, 21, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (48, 15, 15, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (49, 16, 21, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (50, 16, 21, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (51, 16, 10, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (52, 16, 10, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (53, 17, 15, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (54, 17, 2, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (55, 17, 2, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (56, 18, 20, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (57, 18, 20, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (58, 18, 17, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (59, 18, 17, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (60, 18, 13, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (61, 18, 13, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (62, 20, 2, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (63, 20, 2, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (64, 21, 3, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (65, 21, 17, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (66, 21, 21, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (67, 21, 21, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (68, 22, 12, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (69, 22, 12, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (70, 22, 30, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (71, 22, 30, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (72, 23, 21, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (73, 23, 21, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (74, 23, 11, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (75, 23, 11, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (76, 23, 3, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (77, 23, 3, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (78, 23, 3, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (79, 24, 22, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (80, 24, 22, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (81, 24, 5, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (82, 24, 30, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (83, 24, 30, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (84, 25, 27, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (85, 25, 27, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (86, 25, 27, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (87, 25, 5, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (88, 25, 5, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (89, 25, 5, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (90, 28, 6, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (91, 28, 6, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (92, 28, 7, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (93, 29, 3, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (94, 29, 3, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (95, 30, 27, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (96, 30, 27, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (97, 30, 27, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (98, 30, 24, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (99, 30, 24, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (100, 30, 24, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (101, 30, 29, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (102, 31, 15, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (103, 31, 15, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (104, 31, 2, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (105, 31, 2, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (106, 31, 2, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (107, 31, 14, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (108, 31, 14, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (109, 31, 14, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (110, 32, 12, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (111, 32, 12, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (112, 32, 12, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (113, 33, 25, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (114, 33, 25, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (115, 33, 25, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (116, 33, 13, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (117, 34, 2, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (118, 34, 2, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (119, 34, 21, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (120, 35, 28, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (121, 35, 4, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (122, 35, 4, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (123, 35, 10, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (124, 36, 30, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (125, 37, 30, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (126, 37, 30, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (127, 37, 1, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (128, 37, 1, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (129, 37, 1, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (130, 38, 12, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (131, 39, 30, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (132, 39, 30, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (133, 39, 30, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (134, 39, 4, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (135, 41, 30, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (136, 41, 30, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (137, 41, 27, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (138, 41, 27, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (139, 41, 27, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (140, 42, 1, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (141, 42, 1, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (142, 43, 24, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (143, 43, 24, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (144, 43, 20, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (145, 43, 17, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (146, 44, 14, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (147, 44, 14, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (148, 44, 14, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (149, 45, 20, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (150, 45, 18, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (151, 45, 18, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (152, 45, 18, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (153, 46, 14, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (154, 46, 14, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (155, 46, 14, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (156, 46, 1, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (157, 46, 1, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (158, 47, 12, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (159, 47, 12, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (160, 47, 12, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (161, 47, 3, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (162, 47, 17, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (163, 47, 17, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (164, 49, 9, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (165, 49, 24, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (166, 52, 24, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (167, 52, 24, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (168, 52, 24, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (169, 53, 2, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (170, 53, 2, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (171, 54, 6, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (172, 54, 6, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (173, 54, 6, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (174, 54, 27, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (175, 54, 25, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (176, 54, 25, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (177, 54, 25, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (178, 55, 2, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (179, 56, 30, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (180, 56, 30, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (181, 56, 30, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (182, 56, 10, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (183, 56, 10, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (184, 57, 7, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (185, 57, 10, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (186, 57, 10, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (187, 57, 12, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (188, 57, 12, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (189, 59, 15, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (190, 59, 15, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (191, 59, 29, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (192, 59, 29, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (193, 59, 29, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (194, 59, 13, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (195, 59, 13, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (196, 60, 3, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (197, 60, 3, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (198, 60, 3, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (199, 60, 14, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (200, 60, 14, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (201, 61, 22, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (202, 61, 22, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (203, 61, 10, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (204, 66, 12, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (205, 66, 15, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (206, 66, 15, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (207, 66, 15, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (208, 67, 3, 'JSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (209, 67, 3, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (210, 67, 3, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (211, 68, 22, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (212, 68, 6, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (213, 68, 6, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (214, 68, 6, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (215, 68, 1, 'Primary', '4');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (216, 69, 12, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (217, 69, 13, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (218, 69, 19, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (219, 69, 19, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (220, 70, 19, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (221, 71, 13, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (222, 71, 13, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (223, 71, 13, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (224, 71, 11, 'Primary', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (225, 72, 17, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (226, 72, 17, 'SSS', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (227, 72, 17, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (228, 72, 13, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (229, 72, 13, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (230, 72, 13, 'Primary', '5');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (231, 73, 23, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (232, 73, 23, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (233, 73, 30, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (234, 74, 6, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (235, 74, 6, 'Primary', '2');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (236, 74, 6, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (237, 74, 29, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (238, 74, 29, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (239, 74, 29, 'Primary', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (240, 75, 18, 'SSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (241, 75, 18, 'SSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (242, 75, 10, 'JSS', '3');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (243, 75, 10, 'JSS', '1');
INSERT INTO staff_teachingassignment (id, teacher_id, subject_id, level, grade) VALUES (244, 75, 29, 'Primary', '4');

-- ==================================================
-- TABLE 4: staff_classmoderator
-- ==================================================
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (1, 66, 'Primary', '1');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (2, 11, 'Primary', '2');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (3, 20, 'Primary', '3');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (4, 75, 'Primary', '4');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (5, 38, 'Primary', '5');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (6, 2, 'JSS', '1');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (7, 30, 'JSS', '2');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (8, 43, 'JSS', '3');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (9, 44, 'SSS', '1');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (10, 69, 'SSS', '2');
INSERT INTO staff_classmoderator (id, teacher_id, level, grade) VALUES (11, 36, 'SSS', '3');