// Mock data shaped the way the Django REST API is expected to return it:
// each staff record carries its resolved teaching_assignments (Staff <-> Subject,
// with level/grade) and an optional class_moderator record.
export const MOCK_STAFF = [
  {
    id: 1,
    first_name: "Chinedu",
    last_name: "Okafor",
    gender: "Male",
    phone: "0803 221 4567",
    email: "chinedu.okafor@brightpath.edu.ng",
    role: "Teacher",
    employment_type: "Full-time",
    salary: 180000,
    hire_date: "2022-09-01",
    status: "Active",
    teaching_assignments: [
      { subject: { id: 1, name: "Mathematics", code: "MTH" }, level: "JSS", grade: 1 },
      { subject: { id: 1, name: "Mathematics", code: "MTH" }, level: "JSS", grade: 2 },
      { subject: { id: 2, name: "Physics", code: "PHY" }, level: "JSS", grade: 2 },
    ],
    class_moderator: { level: "JSS", grade: 2 },
  },
  {
    id: 2,
    first_name: "Amarachi",
    last_name: "Nwosu",
    gender: "Female",
    phone: "0805 112 3344",
    email: "amarachi.nwosu@brightpath.edu.ng",
    role: "Teacher",
    employment_type: "Full-time",
    salary: 165000,
    hire_date: "2023-01-15",
    status: "Active",
    teaching_assignments: [
      { subject: { id: 3, name: "English Language", code: "ENG" }, level: "Primary", grade: 4 },
      { subject: { id: 3, name: "English Language", code: "ENG" }, level: "Primary", grade: 5 },
    ],
    class_moderator: { level: "Primary", grade: 5 },
  },
  {
    id: 3,
    first_name: "Ibrahim",
    last_name: "Suleiman",
    gender: "Male",
    phone: "0706 998 2211",
    email: "ibrahim.suleiman@brightpath.edu.ng",
    role: "Teacher",
    employment_type: "Part-time",
    salary: 90000,
    hire_date: "2024-03-10",
    status: "Active",
    teaching_assignments: [
      { subject: { id: 4, name: "Chemistry", code: "CHM" }, level: "SSS", grade: 1 },
      { subject: { id: 4, name: "Chemistry", code: "CHM" }, level: "SSS", grade: 2 },
    ],
    class_moderator: null,
  },
  {
    id: 4,
    first_name: "Folake",
    last_name: "Adewumi",
    gender: "Female",
    phone: "0812 445 7890",
    email: "folake.adewumi@brightpath.edu.ng",
    role: "Principal",
    employment_type: "Full-time",
    salary: 350000,
    hire_date: "2018-08-20",
    status: "Active",
    teaching_assignments: [],
    class_moderator: null,
  },
  {
    id: 5,
    first_name: "Emeka",
    last_name: "Eze",
    gender: "Male",
    phone: "0909 334 1122",
    email: "emeka.eze@brightpath.edu.ng",
    role: "Vice Principal",
    employment_type: "Full-time",
    salary: 280000,
    hire_date: "2019-06-11",
    status: "Active",
    teaching_assignments: [],
    class_moderator: null,
  },
  {
    id: 6,
    first_name: "Ngozi",
    last_name: "Ibe",
    gender: "Female",
    phone: "0701 556 9021",
    email: "ngozi.ibe@brightpath.edu.ng",
    role: "Accountant",
    employment_type: "Full-time",
    salary: 150000,
    hire_date: "2021-02-05",
    status: "Active",
    teaching_assignments: [],
    class_moderator: null,
  },
  {
    id: 7,
    first_name: "Yusuf",
    last_name: "Bello",
    gender: "Male",
    phone: "0813 667 4432",
    email: "yusuf.bello@brightpath.edu.ng",
    role: "Librarian",
    employment_type: "Contract",
    salary: 95000,
    hire_date: "2023-09-18",
    status: "Inactive",
    teaching_assignments: [],
    class_moderator: null,
  },
  {
    id: 8,
    first_name: "Chiamaka",
    last_name: "Okonkwo",
    gender: "Female",
    phone: "0802 778 5566",
    email: "chiamaka.okonkwo@brightpath.edu.ng",
    role: "Teacher",
    employment_type: "Full-time",
    salary: 175000,
    hire_date: "2020-11-02",
    status: "Inactive",
    teaching_assignments: [
      { subject: { id: 5, name: "Biology", code: "BIO" }, level: "SSS", grade: 3 },
    ],
    class_moderator: { level: "SSS", grade: 3 },
  },
  {
    id: 9,
    first_name: "Tunde",
    last_name: "Ogunleye",
    gender: "Male",
    phone: "0705 221 8890",
    email: "tunde.ogunleye@brightpath.edu.ng",
    role: "IT Support",
    employment_type: "Full-time",
    salary: 130000,
    hire_date: "2022-04-25",
    status: "Active",
    teaching_assignments: [],
    class_moderator: null,
  },
  {
    id: 10,
    first_name: "Halima",
    last_name: "Garba",
    gender: "Female",
    phone: "0810 998 3345",
    email: "halima.garba@brightpath.edu.ng",
    role: "Teacher",
    employment_type: "Part-time",
    salary: 85000,
    hire_date: "2024-01-08",
    status: "Active",
    teaching_assignments: [
      { subject: { id: 6, name: "Government", code: "GOV" }, level: "SSS", grade: 1 },
      { subject: { id: 7, name: "Economics", code: "ECO" }, level: "SSS", grade: 1 },
    ],
    class_moderator: null,
  },
];
